### ISSUE TITLE
Install metashell on OS X using homebrew

### ISSUE THREAD

**Issue by ortho** [sabel83/metashell#10]
You software have been packaged by [homebrew](brew.sh) project
Users have got the ability to install metashell with simple command
```
$ brew install metashell
``` 

Maybe you'll describe this ability in the documentation.

**Comment by r0mai** [comment]
Wow, thanks!

Docs added in 79e65a5, will be merged soon.

**Comment by r0mai** [comment]
Hi @ortho,

We just released Metashell 2.1.0. (See https://github.com/sabel83/metashell/releases/tag/v2.1.0)

We would be very grateful if you could add this release to Homebrew.

Thank you,
András

**Comment by ortho** [comment]
Good day!

I've just pull request for new version
You can see it here [here](https://github.com/Homebrew/homebrew/pull/43210)

I will inform you after my update will be merged

**Comment by sabel83** [comment]
Thank you

**Comment by ortho** [comment]
Build failed for Mountain Lion. If you have access to Homebrew Jenkins system you can see it there.
If not I can paste error message here.

Yosemite and Mavericks are good!
