### ISSUE TITLE
Failure building on Windows

### ISSUE THREAD

**Issue by eldiener** [sabel83/metashell#11]
Following the metashell instructions for Windows and attempting to run:

cmake .. -G "Visual Studio 12 2013"

from the Metashell 'bin' subdirectory with the latest cmake 3.2.2 I get:

'-- Found CLANG: C:/Programming/VersionControl/metashell/3rd/templight/build/Rele
ase/lib/libclang.imp
LINK : fatal error LNK1561: entry point must be defined
CMake Warning (dev) at cmake/Modules/Compiler.cmake:35 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  lib/data/CMakeLists.txt:20 (enable_warnings)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:49 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  lib/data/CMakeLists.txt:21 (use_cpp11)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:35 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  lib/core/CMakeLists.txt:20 (enable_warnings)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:49 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  lib/core/CMakeLists.txt:21 (use_cpp11)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:35 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  lib/readline/CMakeLists.txt:20 (enable_warnings)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:49 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  lib/readline/CMakeLists.txt:21 (use_cpp11)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:35 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  lib/clang/CMakeLists.txt:20 (enable_warnings)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:49 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  lib/clang/CMakeLists.txt:21 (use_cpp11)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:35 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  app/CMakeLists.txt:20 (enable_warnings)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:49 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  app/CMakeLists.txt:21 (use_cpp11)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:35 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  test/unit/CMakeLists.txt:20 (enable_warnings)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:49 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  test/unit/CMakeLists.txt:21 (use_cpp11)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:35 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  test/system/lib/CMakeLists.txt:20 (enable_warnings)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:49 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  test/system/lib/CMakeLists.txt:21 (use_cpp11)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:35 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  test/system/app/core/CMakeLists.txt:20 (enable_warnings)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:49 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  test/system/app/core/CMakeLists.txt:21 (use_cpp11)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:35 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  test/system/app/mdb/CMakeLists.txt:20 (enable_warnings)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:49 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  test/system/app/mdb/CMakeLists.txt:21 (use_cpp11)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:21 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  3rd/CMakeLists.txt:17 (disable_warnings)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at 3rd/boost/libs/regex/CMakeLists.txt:20 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/Compiler.cmake:49 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  3rd/protobuf/src/CMakeLists.txt:17 (use_cpp11)
This warning is for project developers.  Use -Wno-dev to suppress it.'

An attempt to build metashell from the VC++ metashell.sln fails with:

"1>------ Build started: Project: metashell_core_lib, Configuration: Release Win32 ------
1>  mdb_shell.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(506): error C2664: 'void std::_Func_class<_Ret,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>::_Set(std::_Func_base<_Ret,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &> *)' : cannot convert argument 1 from '_Myimpl *' to 'std::_Func_base<_Ret,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &> *'
1>          with
1>          [
1>              _Ret=void
1>          ]
1>          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(442) : see reference to function template instantiation 'void std::_Func_class<_Ret,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>::_Do_alloc<_Myimpl,_Fret(__thiscall metashell::mdb_shell::* const &)(const std::string &,metashell::iface::displayer &),_Alloc>(_Fty,_Alloc)' being compiled
1>          with
1>          [
1>              _Ret=void
1>  ,            _Fret=void
1>  ,            _Alloc=std::allocator<std::_Func_class<void,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>>
1>  ,            _Fty=void (__thiscall metashell::mdb_shell::* const &)(const std::string &,metashell::iface::displayer &)
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(442) : see reference to function template instantiation 'void std::_Func_class<_Ret,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>::_Do_alloc<_Myimpl,_Fret(__thiscall metashell::mdb_shell::* const &)(const std::string &,metashell::iface::displayer &),_Alloc>(_Fty,_Alloc)' being compiled
1>          with
1>          [
1>              _Ret=void
1>  ,            _Fret=void
1>  ,            _Alloc=std::allocator<std::_Func_class<void,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>>
1>  ,            _Fty=void (__thiscall metashell::mdb_shell::* const &)(const std::string &,metashell::iface::displayer &)
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(442) : see reference to function template instantiation 'void std::_Func_class<_Ret,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>::_Reset_alloc<_Fret,metashell::mdb_shell,const std::string&,metashell::iface::displayer&,std::allocator<std::_Func_class<_Ret,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>>>(_Fret (__thiscall metashell::mdb_shell::* const )(const std::string &,metashell::iface::displayer &),_Alloc)' being compiled
1>          with
1>          [
1>              _Ret=void
1>  ,            _Fret=void
1>  ,            _Alloc=std::allocator<std::_Func_class<void,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>>
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(442) : see reference to function template instantiation 'void std::_Func_class<_Ret,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>::_Reset_alloc<_Fret,metashell::mdb_shell,const std::string&,metashell::iface::displayer&,std::allocator<std::_Func_class<_Ret,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>>>(_Fret (__thiscall metashell::mdb_shell::* const )(const std::string &,metashell::iface::displayer &),_Alloc)' being compiled
1>          with
1>          [
1>              _Ret=void
1>  ,            _Fret=void
1>  ,            _Alloc=std::allocator<std::_Func_class<void,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>>
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(671) : see reference to function template instantiation 'void std::_Func_class<_Ret,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>::_Reset<void,metashell::mdb_shell,const std::string&,metashell::iface::displayer&>(_Fret (__thiscall metashell::mdb_shell::* const )(const std::string &,metashell::iface::displayer &))' being compiled
1>          with
1>          [
1>              _Ret=void
1>  ,            _Fret=void
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\functional(671) : see reference to function template instantiation 'void std::_Func_class<_Ret,metashell::mdb_shell &,const std::string &,metashell::iface::displayer &>::_Reset<void,metashell::mdb_shell,const std::string&,metashell::iface::displayer&>(_Fret (__thiscall metashell::mdb_shell::* const )(const std::string &,metashell::iface::displayer &))' being compiled
1>          with
1>          [
1>              _Ret=void
1>  ,            _Fret=void
1>          ]
1>          C:\Programming\VersionControl\metashell\lib\core\mdb_shell.cpp(137) : see reference to function template instantiation 'std::function<void (metashell::mdb_shell &,const std::string &,metashell::iface::displayer &)>::function<void(__thiscall metashell::mdb_shell::* )(const std::string &,metashell::iface::displayer &)>(_Fx &&)' being compiled
1>          with
1>          [
1>              _Fx=void (__thiscall metashell::mdb_shell::* )(const std::string &,metashell::iface::displayer &)
1>          ]
1>          C:\Programming\VersionControl\metashell\lib\core\mdb_shell.cpp(137) : see reference to function template instantiation 'std::function<void (metashell::mdb_shell &,const std::string &,metashell::iface::displayer &)>::function<void(__thiscall metashell::mdb_shell::* )(const std::string &,metashell::iface::displayer &)>(_Fx &&)' being compiled
1>          with
1>          [
1>              _Fx=void (__thiscall metashell::mdb_shell::* )(const std::string &,metashell::iface::displayer &)
1>          ]
2>------ Build started: Project: metashell, Configuration: Release Win32 ------
3>------ Build started: Project: metashell_unit_test, Configuration: Release Win32 ------
3>LINK : fatal error LNK1181: cannot open input file '..\..\lib\core\Release\metashell_core_lib.lib'
2>LINK : fatal error LNK1181: cannot open input file '..\lib\core\Release\metashell_core_lib.lib'
========== Build: 0 succeeded, 3 failed, 16 up-to-date, 0 skipped =========="

**Comment by sabel83** [comment]
Thank you for the bug report.

I have fixed the Windows build. I can build it and the tests pass as well. Let me know if it works for you as well.

I'll fix the cmake warnings later.

**Comment by eldiener** [comment]
The fix allows me to build metashell.
