### ISSUE TITLE
Syntax for creating a type

### ISSUE THREAD

**Issue by eldiener** [sabel83/metashell#14]
I tried to create a type with:

#include <some_header_file.hpp> // has a class template called some_class_template
typedef some_class_template<template_parameters> some_type;

but received the message:

<stdin>:1:9: fatal error: unknown type name 'some_class_template'

I wanted to use this type in further metashell calculations. Is this possible with metashell ? If so, what is the syntax for doing so ?

**Comment by sabel83** [comment]
This is possible and this is the syntax you should be using. (Further details: http://metashell.readthedocs.org/en/latest/manual/environment/).

I can't tell by this error message if it was Metashell interpreting your command in a wrong way or some issue with the code you are about to test. Could you provide an example that I could reproduce in the web demo or on my computer? (eg. the definition of some_class_template, maybe the entire some_header_file.hpp)

**Comment by eldiener** [comment]
Sorry, my original message was not created correctly. Here is the correct original message ---

I tried to create a type in Metashell with:

    #include <boost/property/property_member_data_value.hpp>
    typedef   prop_member_data<int,p_member_data_class,&p_member_data_class::p_data_int,read_write_tag> p_loc_int_type;

where prop_member_data is a class template in the header file property_member_data_value.hpp.

But I received the message:

    <stdin>:1:9: fatal error: unknown type name 'prop_member_data'

I wanted to use this type in further metashell calculations. Is this possible with metashell ? If so, what is the syntax for doing so ?

**Comment by r0mai** [comment]
My boost version doesn't have this header. My guess is, that you forgot to specify the namespace.
