### ISSUE TITLE
Function templates and metashell expansion

### ISSUE THREAD

**Issue by eldiener** [sabel83/metashell#15]
Is it possible to see what a function template expands to in metashell ? If so, how would I do this ?

**Comment by sabel83** [comment]
You can check the expanded function signature (arguments, return value), the template classes and functions recursively instantiated by your function, but not the body of your function. (see http://metashell.readthedocs.org/en/latest/manual/how_to/#see-what-templates-are-instantiated-by-a-certain-normal-c-expression)
