### ISSUE TITLE
feature request: include a file on startup

### ISSUE THREAD

**Issue by gordonwoodhull** [sabel83/metashell#18]
I'm working with a parser file that I'm slowly building up as I go along. I can't load it more than once per session, of course, so I close metashell and restart it each time I change the file. Then I try parsing some expressions to see if they work.

This is quick and works great. But it would be even more convenient if I could specify on the command line that I always want to start with that file (or a particular command).

Is there a way to configure metashell to do this? I couldn't find a command-line option for this, but I know it has some built-in headers.

Trying to optimize the inner loop of my development here. :wink:

**Comment by r0mai** [comment]
Check out this page:
https://metashell.readthedocs.org/en/latest/reference/pragmas/

You'll probably need  `#msh environment reload`

Alternatively you can turn off precompiled headers (there is a command line parameter for that), which will make metashell to reparse everything on every input. This will slow things down though.

**Comment by gordonwoodhull** [comment]
Thanks @r0mai, I guess this might allow me to reload the same file over again in a session?

I still run into the same error, which I thought was because I was trying to reload the same file, but maybe it is something else:

```
Error parsing source code (<stdin>:  #include "gvparse.cpp")
```

If I restart metashell, it has no problem with the `#include`.

**Comment by gordonwoodhull** [comment]
I don't mind restarting metashell, I'd just like it to reload the same file each time.

**Comment by r0mai** [comment]
This should work. Can you copy paste the console output of the whole session, where you experience this?

That said, your feature request makes sense regardless of this.

**Comment by gordonwoodhull** [comment]
Sure. It's quite simple. I have some bug in my metaprogram and need to edit it iteratively.

```
grodo-mcwoohu:gvparse gordon$ ~/lib/metashell/bin/app/metashell -I ~/lib/mpllibs/ --indent --nosplash
> #msh environment reload
> #include "gvparse.cpp"
> graph_parser::apply<MPLLIBS_STRING("graph g {}")>::type
In file included from <stdin>:1:
In file included from /tmp/just-9CandI/metashell_environment.hpp:7:
In file included from /Users/gordon/src/gvparse/gvparse.cpp:2:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metaparse/keyword.hpp:9:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metaparse/v2/keyword.hpp:10:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metaparse/v2/lit.hpp:9:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metaparse/v2/lit_c.hpp:13:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metaparse/v2/accept_when.hpp:9:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metaparse/v2/get_result.hpp:10:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metamonad/td_metafunction.hpp:9:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metamonad/v1/td_metafunction.hpp:13:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metamonad/v1/exception.hpp:10:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metamonad/v1/algebraic_data_type_tag.hpp:10:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metamonad/v1/impl/rec_equal_to.hpp:9:
In file included from /Users/gordon/lib/mpllibs/mpllibs/metamonad/v1/impl/rec_equal_to_impl.hpp:16:
In file included from /usr/local/include/boost/mpl/vector.hpp:36:
In file included from /usr/local/include/boost/mpl/vector/vector20.hpp:18:
In file included from /usr/local/include/boost/mpl/vector/vector10.hpp:18:
In file included from /usr/local/include/boost/mpl/vector/vector0.hpp:24:
In file included from /usr/local/include/boost/mpl/vector/aux_/clear.hpp:18:
In file included from /usr/local/include/boost/mpl/vector/aux_/vector0.hpp:22:
In file included from /usr/local/include/boost/mpl/vector/aux_/iterator.hpp:19:
In file included from /usr/local/include/boost/mpl/plus.hpp:19:
In file included from /usr/local/include/boost/mpl/aux_/arithmetic_op.hpp:26:
In file included from /usr/local/include/boost/mpl/aux_/numeric_op.hpp:22:
In file included from /usr/local/include/boost/mpl/apply_wrap.hpp:34:
In file included from /usr/local/include/boost/mpl/aux_/include_preprocessed.hpp:37:
/usr/local/include/boost/mpl/aux_/preprocessed/gcc/apply_wrap.hpp:48:7: fatal error: implicit instantiation of undefined template 

// skip hundreds of lines of backtrace ...

/Users/gordon/lib/mpllibs/mpllibs/metaparse/v2/sequence.hpp:33:14: note: template is declared here
      struct sequence;
             ^
1 error generated.

> #include "gvparse.cpp"
Error parsing source code (<stdin>: #include "gvparse.cpp")
```

**Comment by gordonwoodhull** [comment]
Of course, the bug is not simple, but my use of metashell is quite simple.

**Comment by r0mai** [comment]
I see the problem.

Try it like this:
```
$ metashell
> #include "gvparse.cpp"
> /* try stuff => modify gvparse.cpp */
> #msh environment reload
> /* try stuff again, now the modified gvparse.cpp should be loaded */
...repeat if necessary...
```

**Comment by gordonwoodhull** [comment]
Ah, I get it, the pragma causes a reload of any headers already loaded (not allows reloading of them).

Yes, this works great. Will speed up my iterations. :smile_cat: 

And serves the purpose of my request just fine, closing.

**Comment by r0mai** [comment]
Great, happy it works! :)
If you're interested, check out how Abel demonstrates this workflow on a talk in MeetingC++ '14: https://youtu.be/O-7oFSIlGr8 The demo itself starts at 16:47.
